---
- name: Install | Update apt cache
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  changed_when: false
  become: true
  when:
    - ansible_os_family|lower == 'debian'

- name: Install | Manage GIT package
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: Install | CLone remote GIT repository to TMP.
  ansible.builtin.git:
    repo: "{{ stup_url_git_repository }}"
    dest: "/tmp/git_stup"
    update: true
    single_branch: true
    version: "{{ stup_version }}"

- name: Install | Deploy script file
  become: true
  ansible.builtin.copy:
    dest: "{{ stup_path_binary }}"
    src: /tmp/git_stup/stup
    mode: '0755'
    force: true
    remote_src: true

- name: Install | Manage root directory for categories.
  ansible.builtin.file:
    state: directory
    path: "{{ stup_config_categories_root }}"
    owner: "{{ stup_config_owner }}"
    group: "{{ stup_config_group }}"
    mode: '0750'
