---
- name: Converge
  hosts: all
  tasks:
    - name: Molecule | Include variables.
      ansible.builtin.include_vars: ./variables.yml

    - name: Molecule | Include role spreadcat.stup.
      ansible.builtin.include_role:
        name: "spreadcat.stup"
